version: '3'
services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster  
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx512m"
      - xpack.security.enrollment.enabled=true
      - xpack.security.autoconfiguration.enabled=true
      - xpack.security.enabled=false  # Disable security features
      - xpack.security.http.ssl.enabled=false   # Disable SSL for HTTP layer
      - xpack.security.transport.ssl.enabled=false    # Disable SSL for transport layer
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - XPACK_SECURITY_ENABLED=false
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge